name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/ --cov=app

  sast:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bandit (SAST)
        run: |
          pip install bandit
          bandit -r app/ -f html -o bandit_report.html

      - name: Upload Bandit report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit_report.html

      - name: Run OWASP Dependency-Check
        uses: owasp/dependency-check-action@v3
        with:
          project: 'task-manager'
          scan-dir: '.'
          format: 'HTML'

  deploy-staging:
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to staging with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
